---
- hosts: nagios-server
  become: true
  tasks:
    - name: Create /etc/nagios3/conf.d/openstack directory
      file:
        path: /etc/nagios3/conf.d/openstack
        state: directory
    - name: Copy over content into /etc/nagios3/conf.d/openstack/
      copy:
        src: ../Master/openstack/
        dest: /etc/nagios3/conf.d/openstack/
    - name: Copy over plugins to /usr/lib/nagios/plugins/
      copy:
        src: ../Master/plugins/
        dest: /usr/lib/nagios/plugins/
        owner: root
        group: root
        mode: 0755
