#!/bin/bash
#
source openrc
#
vcpu_count=$(openstack hypervisor stats show | grep 'vcpus ' | awk '{ print $4; }' 2>&1)
vcpu_used=$(openstack hypervisor stats show | grep 'vcpus_used' | awk '{ print $4; }' 2>&1)
pct_used=$(($vcpu_used * 100))
pct_used=$(($pct_used / $vcpu_count))
#
if [ "$pct_used" -gt "90" ] ; then
	echo "CRITICAL - $vcpu_used vCPU used out of $vcpu_count - You are at $pct_used % total vCPU consumption"
	exit 2;
fi
#
if [ "$pct_used" -gt "75" ] ; then
        echo "WARNINGL - $vcpu_used vCPU used out of $vcpu_count - You are at $pct_used % total vCPU consumption"
        exit 1;
fi
#
echo "OK - $vcpu_used vCPU used out of $vcpu_count - You are at $pct_used % total vCPU consumption"
exit 0;
#