#!/bin/bash
#
source /usr/lib/nagios/plugins/openrc
#
mem_count=$(openstack hypervisor stats show | grep 'memory_mb ' | awk '{ print $4; }' 2>&1)
mem_used=$(openstack hypervisor stats show | grep 'memory_mb_used' | awk '{ print $4; }' 2>&1)
pct_used=$(($mem_used * 100))
pct_used=$(($pct_used / $mem_count))
#
if [ "$pct_used" -gt "90" ] ; then
	echo "CRITICAL - $mem_used mb used out of $mem_count mb - You are at $pct_used % total memory consumption"
	exit 2;
fi
#
if [ "$pct_used" -gt "75" ] ; then
        echo "WARNINGL - $mem_used mb used out of $mem_count mb - You are at $pct_used % total memory consumption"
        exit 1;
fi
#
echo "OK - $mem_used mb used out of $mem_count mb - You are at $pct_used % total memory consumption"
exit 0;
#