#!/bin/bash
#
source /usr/lib/nagios/plugins/openrc
#
gb_count=$(openstack hypervisor stats show | grep 'local_gb ' | awk '{ print $4; }' 2>&1)
gb_used=$(openstack hypervisor stats show | grep 'local_gb_used' | awk '{ print $4; }' 2>&1)
pct_used=$(($gb_used * 100))
pct_used=$(($pct_used / $gb_count))
#
if [ "$pct_used" -gt "90" ] ; then
	echo "CRITICAL - $gb_used gb used out of $gb_count gb - You are at $pct_used % total local disk consumption"
	exit 2;
fi
#
if [ "$pct_used" -gt "75" ] ; then
        echo "WARNINGL - $gb_used gb used out of $gb_count gb - You are at $pct_used % total local disk consumption"
        exit 1;
fi
#
echo "OK - $gb_used gb used out of $gb_count gb - You are at $pct_used % total local disk consumption"
exit 0;
#