#!/bin/bash
#
source openrc
#
TOKEN=$(openstack token issue | grep -e "id         " | awk '{ print $4; }' 2>&1)
EXPIRES=$(openstack token issue | grep -e "expires" | awk '{ print $4; }' 2>&1)
#
if [ -z "$TOKEN" ]; then
	echo "CRITICAL - Keystone didn't issue a token"
	exit 2;
fi
#
echo "OK - Token ${TOKEN:0:20}... generated and will expire on $EXPIRES"
exit 0;
#