#!/bin/bash
#
source /usr/lib/nagios/plugins/openrc
#
data=$(openstack server list --all-projects 2>&1)
rv=$?
#
if [ "$rv" != "0" ] ; then
    echo $data
    exit $rv
fi
#
echo "$data" | grep -v -e '--------' -e '| ID' -e '^$' | wc -l
#
